spring:
  datasource:
    url: jdbc:h2:mem:a4d3fad0-647e-4e2d-a516-5f750b9d63cf
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true

logging.level: #???? ??
  org.hibernate.SQL: debug #???? 2?
#  org.hibernate.type: trace #???? 2?