spring:
  h2:
    console:
      enabled: true  # H2 콘솔을 활성화합니다.
      path: /h2-console # H2 콘솔에 접근할 경로를 지정합니다. (예: http://localhost:8080/h2-console)

  datasource:
    url: jdbc:h2:mem:a4d3fad0-647e-4e2d-a516-5f750b9d63cf
    username: sa
    password:
    driver-class-name: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true

logging.level: #???? ??
  org.hibernate.SQL: debug #???? 2?
#  org.hibernate.type: trace #???? 2?